package general

import (
	"encoding/base64"
	"fmt"
	"html"
	"os"
	"path/filepath"
	"strings"
)

// payloadToHTML renders a docxPayload into a self-contained HTML string
// that visually approximates a Word document page (A4-like layout with
// matching font sizes, bullet lists, tables, and headings).
func payloadToHTML(p docxPayload) string {
	var sb strings.Builder
	sb.WriteString(`<!DOCTYPE html><html><head><meta charset="UTF-8">
<style>
@page { size: A4; margin: 2.54cm; }
body {
  font-family: 'Segoe UI', 'Microsoft YaHei', 'PingFang SC', Calibri, Arial, sans-serif;
  font-size: 11pt; line-height: 1.6; color: #222;
  max-width: 210mm; margin: 0 auto; padding: 40px 60px;
  background: #fff; box-sizing: border-box;
}
.doc-header { text-align: right; font-size: 9pt; color: #999; margin-bottom: 20px; border-bottom: 1px solid #eee; padding-bottom: 8px; }
h1.doc-title { text-align: center; font-size: 22pt; font-weight: 700; margin: 24px 0 16px; }
h2 { font-size: 16pt; font-weight: 700; margin: 20px 0 10px; border-bottom: 2px solid #2563eb; padding-bottom: 4px; }
h3 { font-size: 14pt; font-weight: 600; margin: 16px 0 8px; }
h4 { font-size: 12pt; font-weight: 600; margin: 12px 0 6px; }
p { margin: 6px 0; }
ul.doc-list { padding-left: 28px; margin: 4px 0; }
ul.doc-list li { margin: 3px 0; }
table { border-collapse: collapse; width: 100%; margin: 12px 0; }
th, td { border: 1px solid #ccc; padding: 6px 10px; text-align: left; font-size: 10pt; }
th { background: #f0f4ff; font-weight: 600; }
tr:nth-child(even) td { background: #fafbfc; }
.doc-image { max-width: 100%; height: auto; margin: 10px 0; }
.doc-footer { margin-top: 30px; border-top: 1px solid #eee; padding-top: 8px; font-size: 9pt; color: #999; text-align: center; }
</style></head><body>
`)

	if p.Header != "" {
		sb.WriteString(fmt.Sprintf(`<div class="doc-header">%s</div>`, html.EscapeString(p.Header)))
	}

	for _, blk := range p.Blocks {
		switch blk.Type {
		case "paragraph":
			writeHTMLParagraph(&sb, blk)
		case "table":
			writeHTMLTable(&sb, blk)
		case "image":
			writeHTMLImage(&sb, blk)
		}
	}

	sb.WriteString(`<div class="doc-footer">Generated by Yunque Agent</div></body></html>`)
	return sb.String()
}

func markdownInlineToHTML(text string) string {
	escaped := html.EscapeString(text)
	escaped = reInlineBoldItalic.ReplaceAllString(escaped, "<b><i>$1</i></b>")
	escaped = reInlineBold.ReplaceAllString(escaped, "<b>$1</b>")
	escaped = reInlineItalic.ReplaceAllString(escaped, "<i>$1</i>")
	return escaped
}

func writeHTMLParagraph(sb *strings.Builder, blk docBlock) {
	rendered := markdownInlineToHTML(blk.Text)
	switch blk.Style {
	case "Title":
		sb.WriteString(fmt.Sprintf(`<h1 class="doc-title">%s</h1>`+"\n", rendered))
	case "Heading1":
		sb.WriteString(fmt.Sprintf("<h2>%s</h2>\n", rendered))
	case "Heading2":
		sb.WriteString(fmt.Sprintf("<h3>%s</h3>\n", rendered))
	case "Heading3":
		sb.WriteString(fmt.Sprintf("<h4>%s</h4>\n", rendered))
	case "ListBullet":
		sb.WriteString(fmt.Sprintf(`<ul class="doc-list"><li>%s</li></ul>`+"\n", rendered))
	default:
		sb.WriteString(fmt.Sprintf("<p>%s</p>\n", rendered))
	}
}

func writeHTMLTable(sb *strings.Builder, blk docBlock) {
	if len(blk.Rows) == 0 {
		return
	}
	sb.WriteString("<table>\n")
	for ri, row := range blk.Rows {
		sb.WriteString("<tr>")
		tag := "td"
		if ri == 0 {
			tag = "th"
		}
		for _, cell := range row {
			sb.WriteString(fmt.Sprintf("<%s>%s</%s>", tag, html.EscapeString(cell), tag))
		}
		sb.WriteString("</tr>\n")
	}
	sb.WriteString("</table>\n")
}

func writeHTMLImage(sb *strings.Builder, blk docBlock) {
	if blk.Path == "" {
		return
	}
	data, err := os.ReadFile(blk.Path)
	if err != nil {
		sb.WriteString(fmt.Sprintf("<p>[Image not found: %s]</p>\n", html.EscapeString(blk.Path)))
		return
	}
	ext := strings.ToLower(filepath.Ext(blk.Path))
	mime := "image/png"
	switch ext {
	case ".jpg", ".jpeg":
		mime = "image/jpeg"
	case ".gif":
		mime = "image/gif"
	case ".webp":
		mime = "image/webp"
	case ".svg":
		mime = "image/svg+xml"
	}
	b64 := base64.StdEncoding.EncodeToString(data)
	sb.WriteString(fmt.Sprintf(`<img class="doc-image" src="data:%s;base64,%s" alt="document image"/>`+"\n", mime, b64))
}

// savePreviewHTML writes the preview HTML to a temp file and returns its path.
func savePreviewHTML(p docxPayload) (string, error) {
	htmlContent := payloadToHTML(p)
	f, err := os.CreateTemp("", "docx_preview_*.html")
	if err != nil {
		return "", err
	}
	defer f.Close()
	if _, err := f.WriteString(htmlContent); err != nil {
		os.Remove(f.Name())
		return "", err
	}
	return f.Name(), nil
}
