package iterate

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sync"
	"time"

	"yunque-agent/internal/agentcore/llm"
)

// ProposalType classifies the kind of improvement proposed.
type ProposalType string

const (
	PropInstallSkill  ProposalType = "install_skill"
	PropAdjustPersona ProposalType = "adjust_persona"
	PropAddMemory     ProposalType = "add_memory"
	PropFixBehavior   ProposalType = "fix_behavior"
)

// ProposalStatus tracks the lifecycle of a proposal.
type ProposalStatus string

const (
	StatusPending  ProposalStatus = "pending"
	StatusApproved ProposalStatus = "approved"
	StatusRejected ProposalStatus = "rejected"
	StatusExecuted ProposalStatus = "executed"
	StatusFailed   ProposalStatus = "failed"
)

// RiskLevel classifies how risky a proposal is.
type RiskLevel int

const (
	RiskLow  RiskLevel = iota // add memory, fix behavior
	RiskMed                   // adjust persona
	RiskHigh                  // install skill, shell operations
)

func (r RiskLevel) String() string {
	switch r {
	case RiskLow:
		return "low"
	case RiskMed:
		return "medium"
	case RiskHigh:
		return "high"
	}
	return "unknown"
}

// Proposal is a single improvement suggestion generated by the engine.
type Proposal struct {
	ID            string         `json:"id"`
	Type          ProposalType   `json:"type"`
	Title         string         `json:"title"`
	Description   string         `json:"description"`
	Risk          RiskLevel      `json:"risk"`
	EstTokens     int            `json:"est_tokens"`     // estimated token cost to execute
	Status        ProposalStatus `json:"status"`
	ReviewSummary string         `json:"review_summary"` // from multi-agent discussion
	Result        string         `json:"result,omitempty"`
	CreatedAt     time.Time      `json:"created_at"`
	ResolvedAt    *time.Time     `json:"resolved_at,omitempty"`
}

// CycleLog records one complete iteration cycle.
type CycleLog struct {
	ID         string     `json:"id"`
	StartedAt  time.Time  `json:"started_at"`
	EndedAt    time.Time  `json:"ended_at"`
	TokensUsed int        `json:"tokens_used"`
	Rounds     int        `json:"rounds"`
	Proposals  []Proposal `json:"proposals"`
	StoppedBy  string     `json:"stopped_by"` // "complete", "budget", "rounds", "cooldown", "error"
}

// LLMCallFunc abstracts an LLM call for the engine (decoupled from concrete client).
type LLMCallFunc func(ctx context.Context, system, user string) (string, int, error) // reply, tokens_used, error

// Config holds iteration engine settings.
type Config struct {
	Enabled     bool
	TokenBudget int           // max tokens per cycle (default 5000)
	MaxRounds   int           // max consecutive iterations (default 3)
	Cooldown    time.Duration // min interval between cycles (default 1h)
	AutoApprove bool          // auto-approve low-risk proposals
	DataDir     string        // persistence dir (data/iterate/)
}

// DefaultConfig returns sensible defaults.
func DefaultConfig() Config {
	return Config{
		TokenBudget: 5000,
		MaxRounds:   3,
		Cooldown:    1 * time.Hour,
	}
}

// Engine drives the self-improvement iteration loop.
type Engine struct {
	mu         sync.Mutex
	cfg        Config
	llmPool    *llm.Pool
	llmCall    LLMCallFunc // injected LLM call (uses Fast tier)
	discuss    *Discusser  // multi-agent discussion (H2)
	onExecute  func(ctx context.Context, p *Proposal) error // execute callback
	onRecord   func(ctx context.Context, summary string)    // write to memory

	lastRunAt  time.Time
	tokensUsed int
	roundsUsed int
	proposals  []Proposal
	cycleLogs  []CycleLog
}

// NewEngine creates an iteration engine.
func NewEngine(cfg Config) *Engine {
	if cfg.TokenBudget <= 0 {
		cfg.TokenBudget = 5000
	}
	if cfg.MaxRounds <= 0 {
		cfg.MaxRounds = 3
	}
	if cfg.Cooldown <= 0 {
		cfg.Cooldown = 1 * time.Hour
	}
	e := &Engine{cfg: cfg}
	e.loadProposals()
	return e
}

// SetLLMPool attaches the multi-model pool.
func (e *Engine) SetLLMPool(pool *llm.Pool) { e.llmPool = pool }

// SetLLMCall attaches the LLM call function (typically using Fast tier).
func (e *Engine) SetLLMCall(fn LLMCallFunc) { e.llmCall = fn }

// SetDiscusser attaches the multi-agent discussion engine.
func (e *Engine) SetDiscusser(d *Discusser) { e.discuss = d }

// SetOnExecute attaches the callback for executing approved proposals.
func (e *Engine) SetOnExecute(fn func(ctx context.Context, p *Proposal) error) { e.onExecute = fn }

// SetOnRecord attaches the callback for recording to memory.
func (e *Engine) SetOnRecord(fn func(ctx context.Context, summary string)) { e.onRecord = fn }

// Enabled returns whether iteration is enabled.
func (e *Engine) Enabled() bool { return e.cfg.Enabled }

// Proposals returns all pending proposals.
func (e *Engine) Proposals() []Proposal {
	e.mu.Lock()
	defer e.mu.Unlock()
	out := make([]Proposal, 0)
	for _, p := range e.proposals {
		if p.Status == StatusPending {
			out = append(out, p)
		}
	}
	return out
}

// AllProposals returns all proposals regardless of status.
func (e *Engine) AllProposals() []Proposal {
	e.mu.Lock()
	defer e.mu.Unlock()
	out := make([]Proposal, len(e.proposals))
	copy(out, e.proposals)
	return out
}

// ApproveProposal marks a proposal as approved.
func (e *Engine) ApproveProposal(id string) bool {
	e.mu.Lock()
	defer e.mu.Unlock()
	for i, p := range e.proposals {
		if p.ID == id && p.Status == StatusPending {
			now := time.Now()
			e.proposals[i].Status = StatusApproved
			e.proposals[i].ResolvedAt = &now
			e.saveProposals()
			return true
		}
	}
	return false
}

// RejectProposal marks a proposal as rejected.
func (e *Engine) RejectProposal(id string) bool {
	e.mu.Lock()
	defer e.mu.Unlock()
	for i, p := range e.proposals {
		if p.ID == id && p.Status == StatusPending {
			now := time.Now()
			e.proposals[i].Status = StatusRejected
			e.proposals[i].ResolvedAt = &now
			e.saveProposals()
			return true
		}
	}
	return false
}

// RunCycle executes one complete self-improvement iteration cycle.
// Steps: introspect → propose → review → execute → verify → record
func (e *Engine) RunCycle(ctx context.Context) (*CycleLog, error) {
	e.mu.Lock()
	if !e.cfg.Enabled {
		e.mu.Unlock()
		return nil, fmt.Errorf("iteration not enabled")
	}
	// Cooldown check
	if time.Since(e.lastRunAt) < e.cfg.Cooldown {
		remaining := e.cfg.Cooldown - time.Since(e.lastRunAt)
		e.mu.Unlock()
		return nil, fmt.Errorf("cooldown active, %s remaining", remaining.Round(time.Second))
	}
	e.lastRunAt = time.Now()
	e.tokensUsed = 0
	e.roundsUsed = 0
	e.mu.Unlock()

	cycleID := fmt.Sprintf("cycle-%d", time.Now().UnixMilli())
	log := &CycleLog{ID: cycleID, StartedAt: time.Now()}

	slog.Info("iterate: cycle starting", "id", cycleID)

	// Step 1: Introspect — review recent interactions, find weaknesses
	weaknesses, err := e.stepIntrospect(ctx)
	if err != nil {
		log.StoppedBy = "error"
		log.EndedAt = time.Now()
		log.TokensUsed = e.tokensUsed
		return log, fmt.Errorf("introspect: %w", err)
	}
	if weaknesses == "" {
		log.StoppedBy = "complete"
		log.EndedAt = time.Now()
		log.TokensUsed = e.tokensUsed
		slog.Info("iterate: no weaknesses found, cycle complete")
		return log, nil
	}

	// Step 2: Propose — generate ≤3 improvement proposals
	proposals, err := e.stepPropose(ctx, weaknesses)
	if err != nil {
		log.StoppedBy = "error"
		log.EndedAt = time.Now()
		log.TokensUsed = e.tokensUsed
		return log, fmt.Errorf("propose: %w", err)
	}

	// Step 3: Review — multi-agent discussion on proposals
	for i := range proposals {
		if e.budgetExhausted() {
			log.StoppedBy = "budget"
			break
		}
		reviewed := e.stepReview(ctx, &proposals[i])
		if !reviewed {
			proposals[i].Status = StatusRejected
		}
	}

	// Step 4+5: Execute approved + verify
	for i := range proposals {
		if proposals[i].Status != StatusApproved && proposals[i].Status != StatusPending {
			continue
		}
		// Auto-approve low-risk if configured, else keep pending for human review
		if proposals[i].Risk == RiskLow && e.cfg.AutoApprove {
			proposals[i].Status = StatusApproved
		} else if proposals[i].Risk > RiskLow && !e.cfg.AutoApprove {
			proposals[i].Status = StatusPending
			continue // needs human approval
		}
		if proposals[i].Status == StatusApproved {
			if err := e.stepExecute(ctx, &proposals[i]); err != nil {
				proposals[i].Status = StatusFailed
				proposals[i].Result = err.Error()
			} else {
				proposals[i].Status = StatusExecuted
			}
		}
	}

	// Step 6: Record — write results to memory + audit
	log.Proposals = proposals
	log.EndedAt = time.Now()
	log.TokensUsed = e.tokensUsed
	log.Rounds = e.roundsUsed
	if log.StoppedBy == "" {
		log.StoppedBy = "complete"
	}

	e.stepRecord(ctx, log)

	// Save proposals
	e.mu.Lock()
	e.proposals = append(e.proposals, proposals...)
	e.cycleLogs = append(e.cycleLogs, *log)
	e.saveProposals()
	e.mu.Unlock()

	slog.Info("iterate: cycle complete",
		"id", cycleID,
		"tokens", e.tokensUsed,
		"proposals", len(proposals),
		"stopped_by", log.StoppedBy,
	)
	return log, nil
}

// ── Step implementations ──

func (e *Engine) stepIntrospect(ctx context.Context) (string, error) {
	if e.llmCall == nil {
		return "", fmt.Errorf("no LLM call function configured")
	}
	system := "你是云雀Agent的自省模块。回顾最近的交互记录，找出Agent的弱点和改进机会。" +
		"只列出最重要的1-3个弱点，每个不超过一句话。如果没有明显弱点，回答\"无需改进\"。"
	user := "请分析Agent最近的表现，找出可以改进的地方。"

	reply, tokens, err := e.llmCall(ctx, system, user)
	if err != nil {
		return "", err
	}
	e.addTokens(tokens)
	e.roundsUsed++

	if reply == "无需改进" || reply == "" {
		return "", nil
	}
	return reply, nil
}

func (e *Engine) stepPropose(ctx context.Context, weaknesses string) ([]Proposal, error) {
	if e.budgetExhausted() {
		return nil, fmt.Errorf("token budget exhausted")
	}

	system := `你是云雀Agent的改进提案生成器。根据发现的弱点，生成具体可执行的改进提案。
每个提案必须是以下类型之一：install_skill, adjust_persona, add_memory, fix_behavior
输出JSON数组，每个元素: {"type": "...", "title": "一句话标题", "description": "具体做什么", "risk": "low/medium/high", "est_tokens": 数字}
最多3个提案。只输出JSON，不要其他文字。`
	user := "发现的弱点:\n" + weaknesses

	reply, tokens, err := e.llmCall(ctx, system, user)
	if err != nil {
		return nil, err
	}
	e.addTokens(tokens)
	e.roundsUsed++

	// Parse proposals from JSON
	var rawProposals []struct {
		Type      string `json:"type"`
		Title     string `json:"title"`
		Desc      string `json:"description"`
		Risk      string `json:"risk"`
		EstTokens int    `json:"est_tokens"`
	}
	if err := json.Unmarshal([]byte(extractJSON(reply)), &rawProposals); err != nil {
		// Try wrapping in array
		if err2 := json.Unmarshal([]byte("["+extractJSON(reply)+"]"), &rawProposals); err2 != nil {
			return nil, fmt.Errorf("parse proposals: %w (raw: %s)", err, reply)
		}
	}

	proposals := make([]Proposal, 0, len(rawProposals))
	for _, rp := range rawProposals {
		if len(proposals) >= 3 {
			break
		}
		risk := RiskLow
		switch rp.Risk {
		case "medium":
			risk = RiskMed
		case "high":
			risk = RiskHigh
		}
		proposals = append(proposals, Proposal{
			ID:        fmt.Sprintf("prop-%d-%d", time.Now().UnixMilli(), len(proposals)),
			Type:      ProposalType(rp.Type),
			Title:     rp.Title,
			Description: rp.Desc,
			Risk:      risk,
			EstTokens: rp.EstTokens,
			Status:    StatusPending,
			CreatedAt: time.Now(),
		})
	}
	return proposals, nil
}

func (e *Engine) stepReview(ctx context.Context, p *Proposal) bool {
	// If we have a multi-agent discusser, use it
	if e.discuss != nil && !e.budgetExhausted() {
		topic := fmt.Sprintf("评审提案: [%s] %s\n描述: %s\n风险级别: %s",
			p.Type, p.Title, p.Description, p.Risk.String())
		conclusion, err := e.discuss.RunDiscussion(ctx, topic, []string{"安全审查员", "用户体验师"})
		if err != nil {
			slog.Warn("iterate: discussion failed", "err", err)
			p.ReviewSummary = "讨论失败: " + err.Error()
			return p.Risk == RiskLow // only auto-approve low risk on failure
		}
		e.addTokens(conclusion.TokensUsed)
		p.ReviewSummary = conclusion.Summary
		return conclusion.Approved
	}

	// Fallback: simple LLM review
	if e.llmCall != nil && !e.budgetExhausted() {
		system := "你是安全审查员。评审以下Agent自我改进提案，回答\"approved\"或\"rejected\"加一句理由。"
		user := fmt.Sprintf("提案: %s\n描述: %s\n风险: %s", p.Title, p.Description, p.Risk.String())
		reply, tokens, err := e.llmCall(ctx, system, user)
		if err == nil {
			e.addTokens(tokens)
			p.ReviewSummary = reply
			return len(reply) > 0 && (reply[0] == 'a' || reply[0] == 'A')
		}
	}

	return p.Risk == RiskLow
}

func (e *Engine) stepExecute(ctx context.Context, p *Proposal) error {
	if e.onExecute == nil {
		return fmt.Errorf("no execute handler configured")
	}
	return e.onExecute(ctx, p)
}

func (e *Engine) stepRecord(ctx context.Context, log *CycleLog) {
	// Write to memory if configured
	if e.onRecord != nil {
		summary := fmt.Sprintf("自我迭代周期 %s: %d个提案, %d tokens, 停止原因: %s",
			log.ID, len(log.Proposals), log.TokensUsed, log.StoppedBy)
		e.onRecord(ctx, summary)
	}

	// Persist cycle log to disk
	if e.cfg.DataDir != "" {
		e.saveCycleLog(log)
	}
}

// ── Budget / round guards ──

func (e *Engine) budgetExhausted() bool {
	return e.tokensUsed >= e.cfg.TokenBudget || e.roundsUsed >= e.cfg.MaxRounds
}

func (e *Engine) addTokens(n int) {
	e.mu.Lock()
	e.tokensUsed += n
	e.mu.Unlock()
}

// ── Persistence ──

func (e *Engine) proposalsPath() string {
	return filepath.Join(e.cfg.DataDir, "proposals.json")
}

func (e *Engine) loadProposals() {
	if e.cfg.DataDir == "" {
		return
	}
	data, err := os.ReadFile(e.proposalsPath())
	if err != nil {
		return
	}
	json.Unmarshal(data, &e.proposals)
}

func (e *Engine) saveProposals() {
	if e.cfg.DataDir == "" {
		return
	}
	os.MkdirAll(e.cfg.DataDir, 0755)
	data, _ := json.MarshalIndent(e.proposals, "", "  ")
	os.WriteFile(e.proposalsPath(), data, 0644)
}

func (e *Engine) saveCycleLog(log *CycleLog) {
	dir := filepath.Join(e.cfg.DataDir, "cycles")
	os.MkdirAll(dir, 0755)
	data, _ := json.MarshalIndent(log, "", "  ")
	path := filepath.Join(dir, log.ID+".json")
	os.WriteFile(path, data, 0644)
}

// ── Helpers ──

// extractJSON tries to extract a JSON array or object from a string.
func extractJSON(s string) string {
	// Find first [ or {
	start := -1
	startChar := byte(0)
	for i := 0; i < len(s); i++ {
		if s[i] == '[' || s[i] == '{' {
			start = i
			startChar = s[i]
			break
		}
	}
	if start < 0 {
		return s
	}
	endChar := byte(']')
	if startChar == '{' {
		endChar = '}'
	}
	depth := 0
	for i := start; i < len(s); i++ {
		if s[i] == startChar {
			depth++
		} else if s[i] == endChar {
			depth--
			if depth == 0 {
				return s[start : i+1]
			}
		}
	}
	return s[start:]
}
