// Yunque Browser Connector — Preset Test Scenarios
// Based on analysis of Manus AI Browser Operator v0.0.48

export const SCENARIOS = [
  {
    id: "google-search",
    name: "Google 搜索",
    description: "在 Google 首页搜索关键词并浏览结果",
    icon: "🔍",
    steps: [
      { type: "browser_navigate", url: "https://www.google.com" },
      { type: "browser_input", target: { strategy: "bySelector", selector: 'textarea[name="q"]' }, text: "Yunque AI Agent", pressEnter: true },
      { type: "browser_screenshot" },
      { type: "browser_scroll", direction: "down" },
      { type: "browser_screenshot" },
    ],
  },
  {
    id: "baidu-search",
    name: "百度搜索",
    description: "在百度首页搜索关键词并浏览结果",
    icon: "🔍",
    steps: [
      { type: "browser_navigate", url: "https://www.baidu.com" },
      { type: "browser_input", target: { strategy: "bySelector", selector: '#kw' }, text: "人工智能", pressEnter: true },
      { type: "browser_screenshot" },
      { type: "browser_scroll", direction: "down" },
      { type: "browser_screenshot" },
    ],
  },
  {
    id: "youtube-search",
    name: "YouTube 搜索",
    description: "在 YouTube 搜索视频并浏览结果",
    icon: "▶️",
    steps: [
      { type: "browser_navigate", url: "https://www.youtube.com" },
      { type: "browser_input", target: { strategy: "bySelector", selector: 'input#search' }, text: "lofi hip hop", pressEnter: true },
      { type: "browser_screenshot" },
      { type: "browser_scroll", direction: "down" },
      { type: "browser_screenshot" },
    ],
  },
  {
    id: "duckduckgo-search",
    name: "DuckDuckGo 搜索",
    description: "在 DuckDuckGo 搜索引擎搜索关键词",
    icon: "🦆",
    steps: [
      { type: "browser_navigate", url: "https://duckduckgo.com" },
      { type: "browser_input", target: { strategy: "bySelector", selector: 'input[name="q"]' }, text: "Yunque AI", pressEnter: true },
      { type: "browser_screenshot" },
    ],
  },
  {
    id: "linkedin-messaging",
    name: "LinkedIn 消息",
    description: "导航到 LinkedIn 消息页面并发送一条问候消息",
    icon: "💼",
    steps: [
      { type: "browser_navigate", url: "https://www.linkedin.com/messaging" },
      { type: "browser_screenshot" },
      { type: "browser_click", target: { strategy: "bySelector", selector: '.msg-form__contenteditable' } },
      { type: "browser_input", text: "Hi! This is a test message from Yunque Agent." },
      { type: "browser_screenshot" },
    ],
  },
  {
    id: "twitter-post",
    name: "Twitter/X 发帖",
    description: "导航到 Twitter 首页并输入一条推文",
    icon: "🐦",
    steps: [
      { type: "browser_navigate", url: "https://x.com/home" },
      { type: "browser_screenshot" },
      { type: "browser_click", target: { strategy: "bySelector", selector: '[data-testid="tweetTextarea_0"]' } },
      { type: "browser_input", text: "Hello World from Yunque Agent! 🐦" },
      { type: "browser_screenshot" },
    ],
  },
  {
    id: "gmail-scroll",
    name: "Gmail 收件箱",
    description: "打开 Gmail 收件箱并滚动浏览邮件",
    icon: "📧",
    steps: [
      { type: "browser_navigate", url: "https://mail.google.com" },
      { type: "browser_screenshot" },
      { type: "browser_scroll", direction: "down" },
      { type: "browser_screenshot" },
    ],
  },
  {
    id: "bing-search",
    name: "Bing 搜索",
    description: "在 Bing 搜索引擎搜索关键词",
    icon: "🔎",
    steps: [
      { type: "browser_navigate", url: "https://www.bing.com" },
      { type: "browser_input", target: { strategy: "bySelector", selector: '#sb_form_q' }, text: "AI Agent 2025", pressEnter: true },
      { type: "browser_screenshot" },
      { type: "browser_scroll", direction: "down" },
      { type: "browser_screenshot" },
    ],
  },
  {
    id: "wikipedia-browse",
    name: "Wikipedia 浏览",
    description: "在 Wikipedia 搜索并浏览一篇文章",
    icon: "📚",
    steps: [
      { type: "browser_navigate", url: "https://en.wikipedia.org" },
      { type: "browser_input", target: { strategy: "bySelector", selector: '#searchInput' }, text: "Artificial intelligence", pressEnter: true },
      { type: "browser_screenshot" },
      { type: "browser_scroll", direction: "down" },
      { type: "browser_scroll", direction: "down" },
      { type: "browser_get_content" },
    ],
  },
  {
    id: "github-browse",
    name: "GitHub 浏览",
    description: "导航到 GitHub 并搜索项目",
    icon: "🐙",
    steps: [
      { type: "browser_navigate", url: "https://github.com" },
      { type: "browser_input", target: { strategy: "bySelector", selector: 'input[name="q"]' }, text: "AI agent framework", pressEnter: true },
      { type: "browser_screenshot" },
      { type: "browser_scroll", direction: "down" },
      { type: "browser_screenshot" },
    ],
  },
  {
    id: "scroll-stress-test",
    name: "滚动压力测试",
    description: "连续滚动到底部和顶部，测试滚动功能稳定性",
    icon: "🔄",
    steps: [
      { type: "browser_navigate", url: "https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)" },
      { type: "browser_scroll", direction: "down", toEnd: true },
      { type: "browser_screenshot" },
      { type: "browser_scroll", direction: "up", toEnd: true },
      { type: "browser_screenshot" },
      { type: "browser_scroll", direction: "down" },
      { type: "browser_scroll", direction: "down" },
      { type: "browser_scroll", direction: "down" },
      { type: "browser_screenshot" },
    ],
  },
  {
    id: "keyboard-test",
    name: "键盘按键测试",
    description: "测试各种键盘按键和组合键",
    icon: "⌨️",
    steps: [
      { type: "browser_navigate", url: "https://www.google.com" },
      { type: "browser_click", target: { strategy: "bySelector", selector: 'textarea[name="q"]' } },
      { type: "browser_press_key", key: "a" },
      { type: "browser_press_key", key: "b" },
      { type: "browser_press_key", key: "c" },
      { type: "browser_press_key", key: "Control+a" },
      { type: "browser_press_key", key: "Backspace" },
      { type: "browser_input", text: "Key test complete" },
      { type: "browser_screenshot" },
    ],
  },
  {
    id: "example-click",
    name: "链接点击测试",
    description: "在 example.com 点击 More Information 链接验证点击功能",
    icon: "🔗",
    steps: [
      { type: "browser_navigate", url: "https://example.com" },
      { type: "browser_screenshot" },
      { type: "browser_click", target: { strategy: "bySelector", selector: "a" } },
      { type: "browser_screenshot" },
    ],
  },
  {
    id: "content-extraction",
    name: "内容提取测试",
    description: "导航到新闻页面并提取页面文本内容",
    icon: "📄",
    steps: [
      { type: "browser_navigate", url: "https://news.ycombinator.com" },
      { type: "browser_screenshot" },
      { type: "browser_get_content" },
      { type: "browser_scroll", direction: "down", toEnd: true },
      { type: "browser_get_content" },
    ],
  },
  {
    id: "user-takeover",
    name: "用户接管测试",
    description: "测试 AI 暂停并让用户接管浏览器的流程",
    icon: "🤝",
    steps: [
      { type: "browser_navigate", url: "https://example.com" },
      { type: "browser_screenshot" },
      { type: "session_status", status: "paused", sessionTitle: "等待用户操作" },
    ],
  },
];
