import { createPacksClient, PacksClientError } from "./packs";

declare const process: { exitCode?: number };
function assert(condition: unknown, message?: string): asserts condition { if (!condition) throw new Error(message || "assertion failed"); }
function assertEqual(actual: unknown, expected: unknown, message?: string): void { if (actual !== expected) throw new Error(message || `expected ${JSON.stringify(actual)} to equal ${JSON.stringify(expected)}`); }
const tests: Array<{ name: string; fn: () => Promise<void> | void }> = [];
function test(name: string, fn: () => Promise<void> | void): void { tests.push({ name, fn }); }
function jsonResponse(body: unknown, init?: ResponseInit): Response { return new Response(JSON.stringify(body), { status: 200, headers: { "Content-Type": "application/json" }, ...init }); }

const backupPack = { manifest: { id: "yunque.pack.backup", name: "Backup Pack", version: "0.1.0", backend: { capabilities: ["backup.info"], routes: ["/v1/backup/info"], routeSpecs: [{ method: "GET", path: "/v1/backup/info", description: "Read backup pack runtime status." }], permissions: ["backup:read"] }, frontend: { menus: [{ key: "backup", label: "备份恢复", path: "/packs/backup", order: 90 }], routes: [{ path: "/packs/backup", component: "backup/BackupPage" }] }, sdk: { typescript: "yunque-client/backup" }, distribution: { packageUrl: "https://packs.yunque.local/backup/backup-pack-0.1.0.tgz", frontendUrl: "https://packs.yunque.local/backup/frontend/remoteEntry.js", sha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef" } }, status: "enabled" };

test("PacksClient lists installed packs for frontend sync", async () => { const calls: { url: string; init?: RequestInit }[] = []; const client = createPacksClient({ baseUrl: "http://localhost:9090/", token: "jwt", fetch: async (url, init) => { calls.push({ url: String(url), init }); return jsonResponse({ packs: [backupPack], enabled: [backupPack], count: 1 }); } }); const installed = await client.installed(); assertEqual(installed.count, 1); assertEqual(installed.packs[0]?.manifest.sdk?.typescript, "yunque-client/backup"); assertEqual(calls[0]?.url, "http://localhost:9090/v1/packs/installed"); assertEqual(new Headers(calls[0]?.init?.headers).get("authorization"), "Bearer jwt"); });


test("PacksClient reads backend module registry", async () => { const calls: { url: string; init?: RequestInit }[] = []; const client = createPacksClient({ baseUrl: "http://localhost:9090", fetch: async (url, init) => { calls.push({ url: String(url), init }); return jsonResponse({ modules: [{ pack_id: "yunque.pack.backup", routes: [{ method: "GET", path: "/v1/backup/info" }] }], count: 1 }); } }); const modules = await client.backendModules(); assertEqual(modules.count, 1); assertEqual(modules.modules[0]?.pack_id, "yunque.pack.backup"); assertEqual(modules.modules[0]?.routes[0]?.path, "/v1/backup/info"); assertEqual(modules.modules[0]?.routes[0]?.method, "GET"); assertEqual(calls[0]?.url, "http://localhost:9090/v1/packs/backend-modules"); });

test("PacksClient reads manifest capability index", async () => { const calls: { url: string; init?: RequestInit }[] = []; const client = createPacksClient({ baseUrl: "http://localhost:9090", fetch: async (url, init) => { calls.push({ url: String(url), init }); return jsonResponse({ generated_at: "2026-05-16T00:00:00Z", packs: 1, enabled_packs: 1, capabilities: 1, enabled_capabilities: 1, entries: [{ capability: "backup.info", pack_id: "yunque.pack.backup", pack_name: "Backup Pack", pack_status: "enabled", enabled: true, optional: true, routes: ["/v1/backup/info"], permissions: ["backup:read"], sdk_typescript: "yunque-client/backup", frontend_paths: ["/packs/backup"] }] }); } }); const capabilities = await client.capabilities(); assertEqual(capabilities.enabled_capabilities, 1); assertEqual(capabilities.entries[0]?.capability, "backup.info"); assertEqual(capabilities.entries[0]?.sdk_typescript, "yunque-client/backup"); assertEqual(calls[0]?.url, "http://localhost:9090/v1/packs/capabilities"); });

test("PacksClient reads installable pack catalog by capability", async () => { const calls: { url: string; init?: RequestInit }[] = []; const client = createPacksClient({ baseUrl: "http://localhost:9090", fetch: async (url, init) => { calls.push({ url: String(url), init }); return jsonResponse({ generated_at: "2026-05-17T00:00:00Z", sources: ["packs/examples", "packs/private"], source_reports: [{ source: "packs/examples", ok: true, manifest_count: 2, matched_entries: 1 }, { source: "packs/private", ok: false, manifest_count: 0, matched_entries: 0, errors: ["pack catalog source packs/private: not found"] }], count: 1, installed: 0, enabled: 0, downloadable: 1, capabilities: 1, capability: "browser.intent.plan", entries: [{ manifest_path: "packs/examples/browser-intent-pack/pack.json", source: "packs/examples", manifest: { id: "yunque.pack.browser-intent", name: "Browser Intent Pack", version: "0.1.0", backend: { capabilities: ["browser.intent.plan"] }, sdk: { typescript: "yunque-client/browser" }, distribution: { packageUrl: "https://packs.yunque.local/browser.tgz", sha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef" } }, installed: false, enabled: false, update_action: "install", downloadable: true }], install_hints: [] }); } }); const catalog = await client.catalog({ capability: "browser.intent.plan" }); assertEqual(catalog.count, 1); assertEqual(catalog.sources[1], "packs/private"); assertEqual(catalog.source_reports?.[0]?.matched_entries, 1); assertEqual(catalog.source_reports?.[1]?.ok, false); assertEqual(catalog.source_reports?.[1]?.errors?.[0], "pack catalog source packs/private: not found"); assertEqual(catalog.entries[0]?.manifest.id, "yunque.pack.browser-intent"); assertEqual(catalog.entries[0]?.downloadable, true); assertEqual(calls[0]?.url, "http://localhost:9090/v1/packs/catalog?capability=browser.intent.plan"); });

test("PacksClient resolves capability ownership and next action", async () => { const calls: { url: string; init?: RequestInit }[] = []; const client = createPacksClient({ baseUrl: "http://localhost:9090", fetch: async (url, init) => { calls.push({ url: String(url), init }); return jsonResponse({ generated_at: "2026-05-17T00:00:00Z", capability: "backup.info", found: true, enabled: true, action: "use", preferred: { capability: "backup.info", pack_id: "yunque.pack.backup", pack_name: "Backup Pack", pack_status: "enabled", enabled: true, optional: true, routes: ["/v1/backup/info"], permissions: ["backup:read"], sdk_typescript: "yunque-client/backup", frontend_paths: ["/packs/backup"] }, entries: [], enabled_entries: [] }); } }); const resolved = await client.resolveCapability("backup.info"); assertEqual(resolved.action, "use"); assertEqual(resolved.preferred?.pack_id, "yunque.pack.backup"); assertEqual(calls[0]?.url, "http://localhost:9090/v1/packs/capabilities/resolve?capability=backup.info"); });

test("PacksClient gates capability availability before runtime use", async () => { const calls: { url: string; init?: RequestInit }[] = []; const client = createPacksClient({ baseUrl: "http://localhost:9090", fetch: async (url, init) => { calls.push({ url: String(url), init }); return jsonResponse({ generated_at: "2026-05-17T00:00:00Z", capability: "backup.info", allowed: true, action: "use", reason: "capability is available through an enabled pack", resolution: { generated_at: "2026-05-17T00:00:00Z", capability: "backup.info", found: true, enabled: true, action: "use", preferred: { capability: "backup.info", pack_id: "yunque.pack.backup", pack_name: "Backup Pack", pack_status: "enabled", enabled: true, optional: true, routes: ["/v1/backup/info"], permissions: ["backup:read"], sdk_typescript: "yunque-client/backup", frontend_paths: ["/packs/backup"] }, entries: [], enabled_entries: [] }, route_audit: [{ pack_id: "yunque.pack.backup", pack_name: "Backup Pack", pack_status: "enabled", enabled: true, status: "ok", declared: true, mounted: true, method: "GET", methods: ["GET"], path: "/v1/backup/info" }] }); } }); const gate = await client.gateCapability("backup.info"); assertEqual(gate.allowed, true); assertEqual(gate.action, "use"); assertEqual(gate.route_audit?.[0]?.status, "ok"); assertEqual(calls[0]?.url, "http://localhost:9090/v1/packs/capabilities/gate?capability=backup.info"); });

test("PacksClient plans multiple capability gates for workflow preflight", async () => { const calls: { url: string; init?: RequestInit }[] = []; const client = createPacksClient({ baseUrl: "http://localhost:9090", fetch: async (url, init) => { calls.push({ url: String(url), init }); return jsonResponse({ generated_at: "2026-05-17T00:00:00Z", capabilities: ["backup.info", "browser.intent"], allowed: false, action: "enable", allowed_count: 1, blocked_count: 1, use_count: 1, enable_count: 1, install_count: 0, route_audit_issue_count: 0, gates: [], required_packs: [{ capability: "backup.info", pack_id: "yunque.pack.backup", pack_name: "Backup Pack", pack_status: "enabled", enabled: true, optional: true }], enable_packs: [{ capability: "browser.intent", pack_id: "yunque.pack.browser-intent", pack_name: "Browser Intent Pack", pack_status: "disabled", enabled: false, optional: true }], catalog_install_hints: [{ manifest_path: "packs/examples/rpa-replay-pack/pack.json", source: "packs/examples", manifest: { id: "yunque.pack.rpa-replay", name: "RPA Replay Pack", version: "0.1.0", backend: { capabilities: ["rpa.replay.plan"] }, distribution: { packageUrl: "https://packs.yunque.local/rpa.tgz", sha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef" } }, installed: false, enabled: false, update_action: "install", downloadable: true }], catalog_download_hints: [{ manifest_path: "packs/examples/rpa-replay-pack/pack.json", source: "packs/examples", manifest: { id: "yunque.pack.rpa-replay", name: "RPA Replay Pack", version: "0.1.0", backend: { capabilities: ["rpa.replay.plan"] }, distribution: { packageUrl: "https://packs.yunque.local/rpa.tgz", sha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef" } }, installed: false, enabled: false, update_action: "install", downloadable: true }], catalog_source_reports: [{ source: "packs/examples", ok: true, manifest_count: 1, matched_entries: 1 }, { source: "packs/private", ok: false, manifest_count: 0, matched_entries: 0, errors: ["pack catalog source packs/private: not found"] }] }); } }); const plan = await client.planCapabilities(["backup.info", "browser.intent"]); assertEqual(plan.allowed, false); assertEqual(plan.action, "enable"); assertEqual(plan.enable_packs?.[0]?.pack_id, "yunque.pack.browser-intent"); assertEqual(plan.catalog_install_hints?.[0]?.manifest.id, "yunque.pack.rpa-replay"); assertEqual(plan.catalog_download_hints?.[0]?.downloadable, true); assertEqual(plan.catalog_source_reports?.[0]?.matched_entries, 1); assertEqual(plan.catalog_source_reports?.[1]?.ok, false); assertEqual(calls[0]?.url, "http://localhost:9090/v1/packs/capabilities/plan?capability=backup.info&capability=browser.intent"); });

test("PacksClient prepares selectable incremental package steps", async () => { const calls: { url: string; init?: RequestInit }[] = []; const client = createPacksClient({ baseUrl: "http://localhost:9090", fetch: async (url, init) => { calls.push({ url: String(url), init }); return jsonResponse({ generated_at: "2026-05-17T00:00:00Z", capabilities: ["backup.info", "rpa.replay.plan"], allowed: false, action: "install", plan: { generated_at: "2026-05-17T00:00:00Z", capabilities: ["backup.info", "rpa.replay.plan"], allowed: false, action: "install", allowed_count: 1, blocked_count: 1, use_count: 1, enable_count: 0, install_count: 1, route_audit_issue_count: 0, gates: [], catalog_source_reports: [{ source: "packs/examples", ok: true, manifest_count: 1, matched_entries: 1 }, { source: "packs/private", ok: false, manifest_count: 0, matched_entries: 0, errors: ["pack catalog source packs/private: not found"] }] }, catalog_source_reports: [{ source: "packs/examples", ok: true, manifest_count: 1, matched_entries: 1 }, { source: "packs/private", ok: false, manifest_count: 0, matched_entries: 0, errors: ["pack catalog source packs/private: not found"] }], steps: [{ action: "download", pack_id: "yunque.pack.rpa-replay", pack_name: "RPA Replay Pack", capability: "rpa.replay.plan", manifest_path: "packs/examples/rpa-replay-pack/pack.json", package_url: "https://packs.yunque.local/rpa.tgz", sha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef", installed: false, enabled: false, downloadable: true }], download_steps: [{ action: "download", pack_id: "yunque.pack.rpa-replay", package_url: "https://packs.yunque.local/rpa.tgz", sha256: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef", installed: false, enabled: false, downloadable: true }], step_count: 1, download_count: 1, enable_count: 0, install_count: 0, route_audit_issue_count: 0, ready_count: 0 }); } }); const prepare = await client.prepareCapabilities(["backup.info", "rpa.replay.plan"]); assertEqual(prepare.action, "install"); assertEqual(prepare.steps[0]?.action, "download"); assertEqual(prepare.download_steps?.[0]?.sha256, "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"); assertEqual(prepare.catalog_source_reports?.[1]?.errors?.[0], "pack catalog source packs/private: not found"); assertEqual(prepare.plan.catalog_source_reports?.[0]?.source, "packs/examples"); assertEqual(calls[0]?.url, "http://localhost:9090/v1/packs/capabilities/prepare?capability=backup.info&capability=rpa.replay.plan"); });

test("PacksClient audits manifest routes against mounted backend modules", async () => { const calls: { url: string; init?: RequestInit }[] = []; const client = createPacksClient({ baseUrl: "http://localhost:9090", fetch: async (url, init) => { calls.push({ url: String(url), init }); return jsonResponse({ generated_at: "2026-05-16T00:00:00Z", packs: 1, enabled_packs: 1, mounted_modules: 1, declared_routes: 2, mounted_routes: 2, ok_routes: 1, missing_routes: 0, method_mismatches: 1, undeclared_routes: 0, entries: [{ pack_id: "yunque.pack.backup", pack_name: "Backup Pack", pack_status: "enabled", enabled: true, status: "ok", declared: true, mounted: true, method: "GET", methods: ["GET"], path: "/v1/backup/info" }] }); } }); const audit = await client.backendRouteAudit(); assertEqual(audit.ok_routes, 1); assertEqual(audit.entries[0]?.status, "ok"); assertEqual(audit.entries[0]?.path, "/v1/backup/info"); assertEqual(calls[0]?.url, "http://localhost:9090/v1/packs/backend-route-audit"); });

test("PacksClient installs local pack manifests", async () => { const calls: { url: string; init?: RequestInit }[] = []; const client = createPacksClient({ baseUrl: "http://localhost:9090", fetch: async (url, init) => { calls.push({ url: String(url), init }); return jsonResponse({ pack: backupPack, status: "enabled" }); } }); const installed = await client.install({ manifestPath: "packs/examples/backup-pack/pack.json" }); assertEqual(installed.status, "enabled"); assertEqual(calls[0]?.url, "http://localhost:9090/v1/packs/install"); assertEqual(calls[0]?.init?.body, JSON.stringify({ manifest_path: "packs/examples/backup-pack/pack.json" })); });

test("PacksClient installs downloaded pack manifests", async () => { const calls: { url: string; init?: RequestInit }[] = []; const client = createPacksClient({ baseUrl: "http://localhost:9090", fetch: async (url, init) => { calls.push({ url: String(url), init }); return jsonResponse({ pack: backupPack, status: "enabled" }); } }); await client.install({ manifestUrl: "https://packs.local/backup/pack.json", source: "stable", download: true }); assertEqual(calls[0]?.init?.body, JSON.stringify({ manifest_url: "https://packs.local/backup/pack.json", source: "stable", download: true })); });


test("PacksClient prunes unreferenced pack artifacts", async () => { const calls: { url: string; init?: RequestInit }[] = []; const client = createPacksClient({ baseUrl: "http://localhost:9090", fetch: async (url, init) => { calls.push({ url: String(url), init }); return jsonResponse({ removed: ["old.tgz"], kept: ["keep.tgz"], removed_count: 1, kept_count: 1 }); } }); const pruned = await client.prune(); assertEqual(pruned.removed_count, 1); assertEqual(calls[0]?.url, "http://localhost:9090/v1/packs/prune"); assertEqual(calls[0]?.init?.body, JSON.stringify({})); });

test("PacksClient mutates pack status with API key", async () => { const calls: { url: string; init?: RequestInit }[] = []; const client = createPacksClient({ baseUrl: "http://localhost:9090", apiKey: "key-1", fetch: async (url, init) => { calls.push({ url: String(url), init }); return jsonResponse({ pack: { ...backupPack, status: "disabled" }, status: "disabled" }); } }); const disabled = await client.disable("yunque.pack.backup"); assertEqual(disabled.status, "disabled"); assertEqual(calls[0]?.url, "http://localhost:9090/v1/packs/disable"); assertEqual(calls[0]?.init?.body, JSON.stringify({ id: "yunque.pack.backup" })); assertEqual(new Headers(calls[0]?.init?.headers).get("x-api-key"), "key-1"); });

test("PacksClient builds frontend menus and routes from enabled packs", async () => { const client = createPacksClient({ baseUrl: "http://localhost:9090", fetch: async () => jsonResponse({ packs: [backupPack], count: 1 }) }); const sync = await client.frontendSync(); assertEqual(sync.menus[0]?.label, "备份恢复"); assertEqual(sync.routes[0]?.component, "backup/BackupPage"); assertEqual(sync.packs[0]?.manifest.id, "yunque.pack.backup"); assertEqual(sync.sdk[0]?.language, "typescript"); assertEqual(sync.sdk[0]?.importPath, "yunque-client/backup"); assertEqual(sync.distributions[0]?.packageUrl, "https://packs.yunque.local/backup/backup-pack-0.1.0.tgz"); assertEqual(sync.distributions[0]?.frontendUrl, "https://packs.yunque.local/backup/frontend/remoteEntry.js"); assertEqual(sync.routeBindings[0]?.path, "/packs/backup"); assertEqual(sync.routeBindings[0]?.packId, "yunque.pack.backup"); assertEqual(sync.routeBindings[0]?.sdk[0]?.importPath, "yunque-client/backup"); assertEqual(sync.backendRouteBindings[0]?.method, "GET"); assertEqual(sync.backendRouteBindings[0]?.path, "/v1/backup/info"); assertEqual(sync.capabilityBindings[0]?.capability, "backup.info"); assertEqual(sync.capabilityBindings[0]?.permissions[0], "backup:read"); assertEqual(sync.capabilityBindings[0]?.frontendPaths[0], "/packs/backup"); });

test("PacksClient resolves route binding for synchronized pack pages", async () => { const client = createPacksClient({ baseUrl: "http://localhost:9090", fetch: async () => jsonResponse({ packs: [backupPack], count: 1 }) }); const binding = await client.routeBinding("/packs/backup/"); assertEqual(binding?.packName, "Backup Pack"); assertEqual(binding?.component, "backup/BackupPage"); assertEqual(binding?.distribution?.frontendUrl, "https://packs.yunque.local/backup/frontend/remoteEntry.js"); });

test("PacksClient reads nested gateway error messages", async () => { const client = createPacksClient({ baseUrl: "http://localhost:9090", fetch: async () => jsonResponse({ error: { code: "PACK_MISSING", message: "pack not installed" } }, { status: 404 }) }); try { await client.enable("missing"); throw new Error("expected enable to reject"); } catch (error) { assert(error instanceof PacksClientError); assertEqual(error.status, 404); assertEqual(error.message, "pack not installed"); } });

let failures = 0; for (const { name, fn } of tests) { try { await fn(); console.log(`ok - ${name}`); } catch (error) { failures += 1; console.error(`not ok - ${name}`); console.error(error); } }
if (failures > 0) process.exitCode = 1; else console.log(`1..${tests.length}`);
