// openapi-gen — Scan gateway routes and emit an OpenAPI 3.1.0 spec skeleton.
//
// Usage:
//
//	go run ./cmd/openapi-gen [gatewayDir] [outputPath]
//
// Defaults:
//   - gatewayDir:  internal/controlplane/gateway
//   - outputPath:  docs/openapi.yaml
//
// The generator extracts every mux.HandleFunc("path", ...) registration in the
// gateway package and produces a path-only spec with sensible defaults
// (security, tags, response codes). Schema bodies are intentionally left as
// `type: object` placeholders — flesh them out per endpoint as needed.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"gopkg.in/yaml.v3"
)

var routePattern = regexp.MustCompile(`mux\.HandleFunc\(\s*"([^"]+)"`)

type openAPISpec struct {
	OpenAPI    string                          `yaml:"openapi"`
	Info       openAPIInfo                     `yaml:"info"`
	Servers    []openAPIServer                 `yaml:"servers"`
	Tags       []openAPITag                    `yaml:"tags,omitempty"`
	Paths      map[string]map[string]operation `yaml:"paths"`
	Components openAPIComponents               `yaml:"components"`
}

type openAPIInfo struct {
	Title       string            `yaml:"title"`
	Description string            `yaml:"description"`
	Version     string            `yaml:"version"`
	License     map[string]string `yaml:"license,omitempty"`
}

type openAPIServer struct {
	URL         string `yaml:"url"`
	Description string `yaml:"description,omitempty"`
}

type openAPITag struct {
	Name        string `yaml:"name"`
	Description string `yaml:"description,omitempty"`
}

type operation struct {
	Tags        []string              `yaml:"tags,omitempty"`
	Summary     string                `yaml:"summary,omitempty"`
	OperationID string                `yaml:"operationId,omitempty"`
	Parameters  []parameter           `yaml:"parameters,omitempty"`
	RequestBody *requestBody          `yaml:"requestBody,omitempty"`
	Responses   map[string]response   `yaml:"responses"`
	Security    []map[string][]string `yaml:"security,omitempty"`
}

type parameter struct {
	Name        string         `yaml:"name"`
	In          string         `yaml:"in"`
	Required    bool           `yaml:"required,omitempty"`
	Schema      map[string]any `yaml:"schema"`
	Description string         `yaml:"description,omitempty"`
}

type requestBody struct {
	Required bool                 `yaml:"required,omitempty"`
	Content  map[string]mediaType `yaml:"content"`
}

type mediaType struct {
	Schema map[string]any `yaml:"schema"`
}

type response struct {
	Description string               `yaml:"description"`
	Content     map[string]mediaType `yaml:"content,omitempty"`
}

type openAPIComponents struct {
	Schemas         map[string]map[string]any `yaml:"schemas"`
	SecuritySchemes map[string]map[string]any `yaml:"securitySchemes"`
}

func main() {
	gatewayDir := filepath.Join("internal", "controlplane", "gateway")
	if len(os.Args) > 1 {
		gatewayDir = os.Args[1]
	}
	outputPath := filepath.Join("docs", "openapi.yaml")
	if len(os.Args) > 2 {
		outputPath = os.Args[2]
	}

	paths, err := extractPaths(gatewayDir)
	if err != nil {
		fmt.Fprintln(os.Stderr, "extract:", err)
		os.Exit(1)
	}
	if len(paths) == 0 {
		fmt.Fprintln(os.Stderr, "no routes found in", gatewayDir)
		os.Exit(1)
	}

	spec := buildSpec(paths)

	out, err := yaml.Marshal(spec)
	if err != nil {
		fmt.Fprintln(os.Stderr, "marshal:", err)
		os.Exit(1)
	}

	if err := os.MkdirAll(filepath.Dir(outputPath), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, "mkdir:", err)
		os.Exit(1)
	}
	header := fmt.Sprintf("# Auto-generated by cmd/openapi-gen — DO NOT EDIT BY HAND.\n# Source: %s\n# Run `go run ./cmd/openapi-gen` to regenerate.\n\n", gatewayDir)
	if err := os.WriteFile(outputPath, append([]byte(header), out...), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "write:", err)
		os.Exit(1)
	}
	fmt.Printf("OK — %d paths (%d auto + %d manual extras) written to %s\n",
		len(spec.Paths), len(paths), len(extraPaths()), outputPath)
}

// shouldInclude decides whether a registered path is a real JSON API endpoint
// worth documenting in OpenAPI. We skip the catch-all UI route, static asset
// prefixes, and any path that doesn't begin with /api, /v1, /webhook, or /healthz.
func shouldInclude(p string) bool {
	if p == "" || p == "/" {
		return false
	}
	switch {
	case strings.HasPrefix(p, "/v1/"),
		strings.HasPrefix(p, "/api/"),
		strings.HasPrefix(p, "/webhook/"),
		p == "/healthz":
		return true
	}
	return false
}

func extractPaths(dir string) ([]string, error) {
	seen := map[string]bool{}
	err := filepath.WalkDir(dir, func(f string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		if filepath.Ext(f) != ".go" || strings.HasSuffix(f, "_test.go") {
			return nil
		}
		data, err := os.ReadFile(f)
		if err != nil {
			return err
		}
		for _, m := range routePattern.FindAllStringSubmatch(string(data), -1) {
			p := m[1]
			if !shouldInclude(p) {
				continue
			}
			// Trailing-slash routes in net/http mux are subtree handlers — they
			// match `/prefix/<anything>`. Convert to an OpenAPI path parameter.
			if strings.HasSuffix(p, "/") && p != "/" {
				p = p + "{id}"
			}
			seen[p] = true
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	out := make([]string, 0, len(seen))
	for p := range seen {
		out = append(out, p)
	}
	sort.Strings(out)
	return out, nil
}

func buildSpec(paths []string) *openAPISpec {
	spec := &openAPISpec{
		OpenAPI: "3.1.0",
		Info: openAPIInfo{
			Title:       "Yunque Agent API",
			Description: "Yunque (云雀) — production AI agent runtime with declarative Cogni shells, multi-channel chat, RAG knowledge, task workflows, and governance.",
			Version:     "v1.0.0",
			License:     map[string]string{"name": "MIT"},
		},
		Servers: []openAPIServer{
			{URL: "http://localhost:9090", Description: "Local default"},
			{URL: "https://yunque.example.com", Description: "Production (replace with your host)"},
		},
		Paths: map[string]map[string]operation{},
		Components: openAPIComponents{
			Schemas: map[string]map[string]any{
				"Error": {
					"type": "object",
					"properties": map[string]any{
						"error": map[string]any{"type": "string", "description": "Error message"},
						"code":  map[string]any{"type": "string", "description": "Machine-readable code"},
					},
					"required": []string{"error"},
				},
				"OK": {
					"type": "object",
					"properties": map[string]any{
						"ok": map[string]any{"type": "boolean"},
					},
				},
				"Empty": {"type": "object"},
			},
			SecuritySchemes: map[string]map[string]any{
				"BearerAuth": {
					"type":         "http",
					"scheme":       "bearer",
					"bearerFormat": "JWT",
					"description":  "Use POST /v1/token to obtain a JWT, then send `Authorization: Bearer <token>`.",
				},
			},
		},
	}

	tagSet := map[string]string{}
	// 1. Auto-discovered paths (from route scanner).
	for _, p := range paths {
		tag := inferTag(p)
		tagSet[tag] = tagDescription(tag)

		methods := inferMethods(p)
		ops := map[string]operation{}
		for _, m := range methods {
			ops[m] = defaultOperation(p, m, tag, !isPublic(p))
		}
		spec.Paths[p] = ops
	}

	// 2. Extra paths (handler-internal subroutes the scanner can't see).
	// These take precedence: if an extra path matches an auto-generated
	// path, the extra entry replaces the auto-generated method.
	autoSubsumed := map[string]bool{} // paths the extras now own end-to-end
	for _, e := range extraPaths() {
		ops, ok := spec.Paths[e.Path]
		if !ok {
			ops = map[string]operation{}
			spec.Paths[e.Path] = ops
		}
		// If we're filling in this extra path for the first time, drop any
		// auto-generated default method entries for the same path so we don't
		// keep stale GET/POST placeholders next to precise overrides.
		if !autoSubsumed[e.Path] {
			for k := range ops {
				delete(ops, k)
			}
			autoSubsumed[e.Path] = true
		}
		op := defaultOperation(e.Path, e.Method, e.Tag, !isPublic(e.Path))
		op.Summary = e.Summary
		op.OperationID = e.OperationID
		ops[e.Method] = op
		tagSet[e.Tag] = tagDescription(e.Tag)
	}

	// 3. Schema overrides (precise request/response bodies for hand-curated
	//    endpoints). Applied last so they win over auto-generated placeholders
	//    AND extra-path defaults.
	for _, s := range schemaOverrides() {
		ops, ok := spec.Paths[s.Path]
		if !ok {
			continue
		}
		op, ok := ops[s.Method]
		if !ok {
			continue
		}
		if s.RequestSchema != nil {
			op.RequestBody = &requestBody{
				Required: true,
				Content: map[string]mediaType{
					"application/json": {Schema: s.RequestSchema},
				},
			}
		}
		if s.Response200 != nil {
			resp := op.Responses["200"]
			resp.Content = map[string]mediaType{
				"application/json": {Schema: s.Response200},
			}
			if s.Response200Desc != "" {
				resp.Description = s.Response200Desc
			}
			op.Responses["200"] = resp
		}
		ops[s.Method] = op
	}

	tags := make([]openAPITag, 0, len(tagSet))
	for name, desc := range tagSet {
		tags = append(tags, openAPITag{Name: name, Description: desc})
	}
	sort.Slice(tags, func(i, j int) bool { return tags[i].Name < tags[j].Name })
	spec.Tags = tags

	return spec
}

// inferTag picks a tag from the second path segment when present, otherwise
// the first. It also normalises a few aliases (api/skillhub → skillhub).
func inferTag(p string) string {
	parts := strings.Split(strings.Trim(p, "/"), "/")
	if len(parts) == 0 {
		return "default"
	}
	switch parts[0] {
	case "api":
		if len(parts) >= 2 {
			return parts[1]
		}
		return "api"
	case "v1":
		if len(parts) >= 2 {
			return parts[1]
		}
		return "v1"
	case "webhook":
		return "webhook"
	case "healthz":
		return "system"
	}
	return parts[0]
}

func tagDescription(tag string) string {
	descs := map[string]string{
		"chat":          "Chat & conversations (SSE streaming, agentic mode, WebSocket)",
		"tasks":         "Task runtime, workflows, missions, state kernel",
		"memory":        "Multi-layer memory store, search, embeddings",
		"graph":         "Knowledge graph (entities, relations, context)",
		"knowledge":     "RAG knowledge base (sources, ingest, search)",
		"plugins":       "Plugin lifecycle (CRUD, toggle, reload)",
		"skills":        "Skills runtime + dynamic skill suggestions",
		"skillhub":      "Skill marketplace (search, install, versions)",
		"market":        "Skill market analytics",
		"triggers":      "Event triggers (legacy + v2)",
		"cron":          "Cron scheduling",
		"scheduler":     "Generic job scheduler",
		"tools":         "Tool execution (subprocess)",
		"sandbox":       "Sandbox & desktop session (admin)",
		"audit":         "Audit log (tail, verify, stats)",
		"trust":         "Trust scoring",
		"iterate":       "Self-improvement proposals",
		"cost":          "Cost tracking & budgets",
		"usage":         "Usage & quota",
		"providers":     "LLM providers, presets, smart router",
		"router":        "Router stats",
		"reverie":       "Inner monologue / journaling",
		"rbac":          "Role-based access control",
		"approvals":     "Human-in-the-loop approval queue",
		"setup":         "First-run setup wizard",
		"sessions":      "Session queue",
		"events":        "SSE event stream",
		"trace":         "Execution traces",
		"browser":       "Browser engine + extension connector",
		"ide":           "IDE supervisor plugin",
		"persona":       "Persona, presets, modes",
		"planner":       "Planner checkpoints, recovery plans, and execution-state read models",
		"workflows":     "Workflow DAG engine",
		"notify":        "Notification channels",
		"connectors":    "External connectors",
		"system":        "Health & version",
		"federation":    "Federated agent network (peers, discover, broadcast)",
		"cognis":        "Cogni declarative AI-cognition shells",
		"modules":       "Hot-pluggable modules",
		"speech":        "TTS / STT",
		"heartbeat":     "Liveness heartbeat",
		"backup":        "Backup & restore",
		"settings":      "Runtime settings",
		"models":        "Model registry",
		"identity":      "Identity resolution",
		"embeddings":    "Embedding computation",
		"search":        "Web search providers",
		"emotion":       "Emotion analysis & stickers",
		"react":         "React handler",
		"sticker":       "Sticker dispatch",
		"channels":      "Channel groups",
		"inbox":         "Inbox messages",
		"webhook":       "Inbound webhooks (Feishu etc.)",
		"webchat":       "Embeddable web chat widget",
		"ws":            "WebSocket endpoint",
		"token":         "JWT token generation",
		"conversations": "Conversation history",
		"fork":          "Conversation fork & branches",
		"subagent":      "Subagent dispatch",
		"bots":          "Bot directory",
		"reflect":       "Reflection / experience replay",
		"documents":     "Document generation",
		"missions":      "Mission parser",
		"state":         "State kernel snapshots",
		"metrics":       "Metrics (JSON + Prometheus)",
		"cache":         "Cache stats",
		"tenants":       "Tenant management",
		"upload":        "File upload",
		"config":        "Config reload",
		"desktop":       "Desktop integration",
		"tori":          "Tori (sister product) bind",
		"breaker":       "Circuit breaker reset",
		"files":         "Output file listing",
		"version":       "Version info",
		"quota":         "Quota management",
	}
	if d, ok := descs[tag]; ok {
		return d
	}
	return ""
}

// isPublic returns true for endpoints registered without requireAuth.
// This is best-effort; verify against the actual handler when generating SDKs.
func isPublic(p string) bool {
	switch {
	case p == "/healthz",
		p == "/v1/version",
		p == "/v1/token",
		strings.HasPrefix(p, "/webhook/"),
		strings.HasPrefix(p, "/v1/webchat/widget"):
		return true
	}
	return false
}

// inferMethods picks the most likely HTTP methods for a path. Many gateway
// handlers do internal `switch r.Method`, so we err on the side of including
// both GET and POST when uncertain. Refine per-endpoint after generation.
func inferMethods(p string) []string {
	switch {
	case strings.Contains(p, "/stream"),
		strings.Contains(p, "/events/stream"),
		p == "/healthz",
		strings.HasSuffix(p, "/widget.js"):
		return []string{"get"}

	case strings.HasSuffix(p, "/list"),
		strings.HasSuffix(p, "/stats"),
		strings.HasSuffix(p, "/info"),
		strings.HasSuffix(p, "/status"),
		strings.HasSuffix(p, "/health"),
		strings.HasSuffix(p, "/schema"),
		strings.HasSuffix(p, "/detect"),
		strings.HasSuffix(p, "/templates"),
		strings.HasSuffix(p, "/voices"),
		strings.HasSuffix(p, "/jobs"),
		strings.HasSuffix(p, "/peers"),
		strings.HasSuffix(p, "/recent"),
		strings.HasSuffix(p, "/my-roles"),
		strings.HasSuffix(p, "/usage"),
		strings.HasSuffix(p, "/scores"),
		strings.HasSuffix(p, "/proposals"),
		strings.HasSuffix(p, "/trail"),
		strings.HasSuffix(p, "/breakdown"),
		strings.HasSuffix(p, "/history"),
		strings.HasSuffix(p, "/alerts"),
		strings.HasSuffix(p, "/budget"),
		strings.HasSuffix(p, "/summary"),
		strings.HasSuffix(p, "/timeline"),
		strings.HasSuffix(p, "/strategies"),
		strings.HasSuffix(p, "/experiences"),
		strings.HasSuffix(p, "/journal"),
		strings.HasSuffix(p, "/targets"),
		strings.HasSuffix(p, "/actions"),
		strings.HasSuffix(p, "/pending"),
		strings.HasSuffix(p, "/screenshot"),
		strings.HasSuffix(p, "/screenshot/latest"),
		strings.HasSuffix(p, "/installed"),
		strings.HasSuffix(p, "/trending"),
		strings.HasSuffix(p, "/detail"),
		strings.HasSuffix(p, "/check-updates"),
		strings.HasSuffix(p, "/versions"),
		strings.HasSuffix(p, "/analytics"),
		strings.HasSuffix(p, "/patterns"),
		strings.HasSuffix(p, "/metrics"),
		strings.HasSuffix(p, "/prometheus"),
		strings.HasSuffix(p, "/version"),
		strings.HasSuffix(p, "/files"),
		strings.HasSuffix(p, "/download"),
		strings.HasSuffix(p, "/poll"),
		strings.HasSuffix(p, "/profiles"),
		strings.HasSuffix(p, "/providers"),
		strings.HasSuffix(p, "/models"),
		strings.HasSuffix(p, "/inbox"),
		strings.HasSuffix(p, "/skills"),
		strings.HasSuffix(p, "/groups"),
		strings.HasSuffix(p, "/channels"),
		strings.HasSuffix(p, "/persona"),
		strings.HasSuffix(p, "/presets"),
		strings.HasSuffix(p, "/features"),
		strings.HasSuffix(p, "/stickers"),
		strings.HasSuffix(p, "/modes"),
		strings.HasSuffix(p, "/mode/current"),
		strings.HasSuffix(p, "/instances"),
		strings.HasSuffix(p, "/runs"),
		strings.HasSuffix(p, "/discovery"),
		strings.HasSuffix(p, "/capabilities"),
		strings.HasSuffix(p, "/queue"),
		strings.HasSuffix(p, "/scenarios"),
		strings.HasSuffix(p, "/threads"),
		strings.HasSuffix(p, "/memory"),
		strings.HasSuffix(p, "/gaps"),
		strings.HasSuffix(p, "/goals"),
		strings.HasSuffix(p, "/focus"),
		strings.HasSuffix(p, "/resources"),
		strings.HasSuffix(p, "/messages"),
		strings.HasSuffix(p, "/check"),
		strings.HasSuffix(p, "/config"),
		strings.HasSuffix(p, "/logs"),
		strings.HasSuffix(p, "/economics"),
		strings.HasSuffix(p, "/evolution"),
		strings.HasSuffix(p, "/workflows"),
		strings.HasSuffix(p, "/experience"),
		strings.HasSuffix(p, "/cognis"),
		strings.HasSuffix(p, "/federation"),
		strings.HasSuffix(p, "/sources"),
		strings.HasSuffix(p, "/dirs"),
		strings.HasSuffix(p, "/branch"),
		strings.HasSuffix(p, "/widget.js"),
		strings.HasSuffix(p, "/audit/tail"):
		return []string{"get"}

	case strings.HasSuffix(p, "/add"),
		strings.HasSuffix(p, "/create"),
		strings.HasSuffix(p, "/run"),
		strings.HasSuffix(p, "/emit"),
		strings.HasSuffix(p, "/cancel"),
		strings.HasSuffix(p, "/pause"),
		strings.HasSuffix(p, "/resume"),
		strings.HasSuffix(p, "/restart"),
		strings.HasSuffix(p, "/remove"),
		strings.HasSuffix(p, "/delete"),
		strings.HasSuffix(p, "/update"),
		strings.HasSuffix(p, "/upload"),
		strings.HasSuffix(p, "/ingest"),
		strings.HasSuffix(p, "/import-url"),
		strings.HasSuffix(p, "/import-repo"),
		strings.HasSuffix(p, "/install"),
		strings.HasSuffix(p, "/uninstall"),
		strings.HasSuffix(p, "/reload"),
		strings.HasSuffix(p, "/toggle"),
		strings.HasSuffix(p, "/test"),
		strings.HasSuffix(p, "/test-provider"),
		strings.HasSuffix(p, "/test-config"),
		strings.HasSuffix(p, "/apply"),
		strings.HasSuffix(p, "/install-component"),
		strings.HasSuffix(p, "/exec"),
		strings.HasSuffix(p, "/probe"),
		strings.HasSuffix(p, "/desktop"),
		strings.HasSuffix(p, "/desktop/destroy"),
		strings.HasSuffix(p, "/kill"),
		strings.HasSuffix(p, "/grant"),
		strings.HasSuffix(p, "/reset"),
		strings.HasSuffix(p, "/approve"),
		strings.HasSuffix(p, "/reject"),
		strings.HasSuffix(p, "/decide"),
		strings.HasSuffix(p, "/deny"),
		strings.HasSuffix(p, "/trigger"),
		strings.HasSuffix(p, "/compact"),
		strings.HasSuffix(p, "/resolve"),
		strings.HasSuffix(p, "/parse"),
		strings.HasSuffix(p, "/think"),
		strings.HasSuffix(p, "/navigate"),
		strings.HasSuffix(p, "/screenshot"),
		strings.HasSuffix(p, "/ocr"),
		strings.HasSuffix(p, "/scenarios/run"),
		strings.HasSuffix(p, "/action"),
		strings.HasSuffix(p, "/session"),
		strings.HasSuffix(p, "/connect"),
		strings.HasSuffix(p, "/disconnect"),
		strings.HasSuffix(p, "/execute"),
		strings.HasSuffix(p, "/bind"),
		strings.HasSuffix(p, "/unbind"),
		strings.HasSuffix(p, "/import"),
		strings.HasSuffix(p, "/export"),
		strings.HasSuffix(p, "/generate"),
		strings.HasSuffix(p, "/instantiate"),
		strings.HasSuffix(p, "/expose"),
		strings.HasSuffix(p, "/unexpose"),
		strings.HasSuffix(p, "/discover"),
		strings.HasSuffix(p, "/delegate"),
		strings.HasSuffix(p, "/broadcast"),
		strings.HasSuffix(p, "/receive"),
		strings.HasSuffix(p, "/evolve"),
		strings.HasSuffix(p, "/workflow"),
		strings.HasSuffix(p, "/record"),
		strings.HasSuffix(p, "/queue/cancel"),
		strings.HasSuffix(p, "/rollback"),
		strings.HasSuffix(p, "/mode"),
		strings.HasSuffix(p, "/policy"),
		strings.HasSuffix(p, "/policy/check"),
		strings.HasSuffix(p, "/switch-model"),
		strings.HasSuffix(p, "/audit/verify"),
		strings.HasSuffix(p, "/heartbeat/trigger"),
		strings.HasSuffix(p, "/iterate/trigger"),
		strings.HasSuffix(p, "/disable"),
		strings.HasSuffix(p, "/enable"),
		strings.HasSuffix(p, "/register"),
		strings.HasSuffix(p, "/scan"),
		strings.HasSuffix(p, "/dynamic/approve"),
		strings.HasSuffix(p, "/dynamic/reject"),
		strings.HasSuffix(p, "/open-folder"),
		strings.HasSuffix(p, "/feishu"):
		return []string{"post"}
	}
	return []string{"get", "post"}
}

func defaultOperation(path, method, tag string, auth bool) operation {
	op := operation{
		Tags:        []string{tag},
		Summary:     fmt.Sprintf("%s %s", strings.ToUpper(method), path),
		OperationID: makeOperationID(method, path),
		Parameters:  pathParams(path),
		Responses: map[string]response{
			"200": {
				Description: "Success",
				Content: map[string]mediaType{
					"application/json": {Schema: map[string]any{"type": "object"}},
				},
			},
			"400": {Description: "Bad request", Content: errContent()},
		},
	}
	if auth {
		op.Responses["401"] = response{Description: "Unauthorized", Content: errContent()}
	}
	op.Responses["500"] = response{Description: "Internal error", Content: errContent()}

	if method == "post" || method == "put" || method == "patch" {
		op.RequestBody = &requestBody{
			Required: false,
			Content: map[string]mediaType{
				"application/json": {Schema: map[string]any{"type": "object"}},
			},
		}
	}
	if auth {
		op.Security = []map[string][]string{{"BearerAuth": {}}}
	}
	return op
}

// pathParams extracts {name} placeholders from a path and returns them as
// path parameters with a generic string schema.
func pathParams(path string) []parameter {
	var out []parameter
	parts := strings.Split(path, "/")
	for _, p := range parts {
		if strings.HasPrefix(p, "{") && strings.HasSuffix(p, "}") && len(p) > 2 {
			name := p[1 : len(p)-1]
			out = append(out, parameter{
				Name:        name,
				In:          "path",
				Required:    true,
				Schema:      map[string]any{"type": "string"},
				Description: fmt.Sprintf("Path parameter `%s`", name),
			})
		}
	}
	return out
}

func errContent() map[string]mediaType {
	return map[string]mediaType{
		"application/json": {Schema: map[string]any{"$ref": "#/components/schemas/Error"}},
	}
}

func makeOperationID(method, path string) string {
	parts := strings.Split(strings.Trim(path, "/"), "/")
	cleaned := make([]string, 0, len(parts)+1)
	cleaned = append(cleaned, method)
	for _, p := range parts {
		p = strings.ReplaceAll(p, "-", "_")
		p = strings.ReplaceAll(p, ".", "_")
		p = strings.ReplaceAll(p, "{", "")
		p = strings.ReplaceAll(p, "}", "")
		if p == "" {
			continue
		}
		cleaned = append(cleaned, p)
	}
	return strings.Join(cleaned, "_")
}
