package belief

import (
	"fmt"
	"math"
	"strings"
	"sync"
	"time"
)

// UpdateKind describes the type of belief update.
type UpdateKind string

const (
	UpdateReinforce    UpdateKind = "reinforce"     // strengthens existing belief
	UpdateWeaken       UpdateKind = "weaken"        // weakens existing belief
	UpdateValenceShift UpdateKind = "valence_shift" // changes emotional charge
	UpdateResolution   UpdateKind = "resolution"    // tension resolved (merge/archive)
	UpdateEvidence     UpdateKind = "evidence"      // adds evidence without changing strength
	UpdateCreation     UpdateKind = "creation"      // creates a new belief node
	UpdateSuppression  UpdateKind = "suppression"   // temporarily suppress a belief
)

// UpdateRecord is a single atomic update to the belief system.
type UpdateRecord struct {
	Kind      UpdateKind `json:"kind"`
	TargetID  string     `json:"target_id"`
	Delta     float64    `json:"delta,omitempty"`      // strength delta for reinforce/weaken
	ValenceTo float64    `json:"valence_to,omitempty"` // new valence for shift
	Evidence  string     `json:"evidence,omitempty"`   // evidence string for evidence update
	Source    Source     `json:"source"`               // what triggered this update
	Note      string     `json:"note,omitempty"`       // human-readable note
}

// BeliefUpdateProposal is a proposed change to the belief graph.
// It is generated by the engine in response to an interaction,
// and must be applied via Engine.Apply.
type BeliefUpdateProposal struct {
	Updates         []UpdateRecord `json:"updates"`
	ProposedNew     []*BeliefNode  `json:"proposed_new,omitempty"`
	ProposedTension *BeliefNode    `json:"proposed_tension,omitempty"`
	Reason          string         `json:"reason"`
	Provenance      string         `json:"provenance"` // e.g. "interaction:msg_123"
}

// Scorer evaluates LLM-generated text for alignment with active beliefs.
// It is the bridge between the belief engine and the LLM output layer.
type Scorer struct {
	graph     *BeliefGraph
	threshold float64
}

// NewScorer creates a scorer from the given graph.
func NewScorer(g *BeliefGraph, threshold float64) *Scorer {
	if threshold <= 0 {
		threshold = 0.3
	}
	return &Scorer{graph: g, threshold: threshold}
}

// ScoreAlignment checks whether a piece of text aligns with active beliefs.
// Returns a score in [0, 1] where 1 means perfectly aligned.
// This is a simple heuristic; the real alignment check integrates with the LLM.
func (s *Scorer) ScoreAlignment(text string, activeIDs []string) float64 {
	if s.graph == nil || len(activeIDs) == 0 {
		return 1.0 // no active beliefs = no constraint
	}

	textLower := strings.ToLower(text)
	var total float64
	var count int

	for _, id := range activeIDs {
		node := s.graph.Get(id)
		if node == nil {
			continue
		}

		// A simple keyword overlap heuristic.
		// In production, this would use embedding similarity or LLM judgment.
		words := strings.Fields(strings.ToLower(node.Statement))
		var hits int
		var considered int
		for _, w := range words {
			if len(w) <= 2 {
				continue // skip short words
			}
			considered++
			if strings.Contains(textLower, w) {
				hits++
			}
		}

		if considered == 0 {
			continue
		}
		overlap := float64(hits) / float64(considered)
		if overlap > 1.0 {
			overlap = 1.0
		}
		total += overlap
		count++
	}

	if count == 0 {
		return 1.0
	}
	return total / float64(count)
}

// Threshold returns the alignment threshold below which text is considered
// out of alignment with beliefs.
func (s *Scorer) Threshold() float64 { return s.threshold }

// Engine is the belief update and evaluation engine.
//
// Responsibilities:
//   - Accept interaction context and produce a BeliefUpdateProposal
//   - Apply proposals atomically to the graph
//   - Evaluate the current state against a turn request
//   - Compute a Tendency direction
//   - Maintain an audit log of changes
//
// The engine does NOT make LLM calls directly. Instead, it exposes
// primitives that the integration layer (cmd/agent) can use to build
// prompts and process responses.
type Engine struct {
	graph *BeliefGraph
	mu    sync.RWMutex

	// decayRate controls how quickly unsupported beliefs weaken (per day).
	decayRate float64

	// maxTensionAge controls how long unresolved tensions survive before
	// being flagged for reflection.
	maxTensionAge time.Duration

	// auditLog records all applied updates.
	auditLog []AuditEntry
}

// NewEngine creates a belief engine over the given graph.
func NewEngine(graph *BeliefGraph) *Engine {
	return &Engine{
		graph:         graph,
		decayRate:     0.05,
		maxTensionAge: 24 * time.Hour,
	}
}

// SetDecayRate adjusts the daily strength decay for unsupported beliefs.
func (e *Engine) SetDecayRate(rate float64) {
	e.mu.Lock()
	defer e.mu.Unlock()
	e.decayRate = math.Max(0, math.Min(1, rate))
}

// SetMaxTensionAge adjusts the maximum age for unresolved tensions.
func (e *Engine) SetMaxTensionAge(d time.Duration) {
	e.mu.Lock()
	defer e.mu.Unlock()
	e.maxTensionAge = d
}

// Graph returns the underlying graph (read-only accessor).
func (e *Engine) Graph() *BeliefGraph { return e.graph }

// ── Proposal Generation ──

// EvaluateInteraction processes an interaction and produces an ActivateResult
// describing which beliefs are relevant to the current context.
//
// This does NOT modify the graph — it only reads.
func (e *Engine) EvaluateInteraction(message string, tags []string) (*ActivateResult, error) {
	e.mu.RLock()
	defer e.mu.RUnlock()

	if e.graph == nil || e.graph.Size() == 0 {
		return &ActivateResult{}, nil
	}

	result := &ActivateResult{}
	msgLower := strings.ToLower(message)

	for _, node := range e.graph.List() {
		if node.Strength < 0.1 {
			continue // beliefs below threshold aren't active
		}

		// Simple keyword-based activation.
		// In production, this would use semantic similarity.
		stmtLower := strings.ToLower(node.Statement)
		words := strings.Fields(stmtLower)
		matched := false
		for _, w := range words {
			if len(w) > 2 && strings.Contains(msgLower, w) {
				matched = true
				break
			}
		}

		if !matched && len(tags) > 0 {
			// Check tags as secondary signal.
			for _, tag := range tags {
				if strings.Contains(stmtLower, strings.ToLower(tag)) {
					matched = true
					break
				}
			}
		}

		if matched {
			result.ActiveBeliefs = append(result.ActiveBeliefs, node.ID)

			switch node.Kind {
			case KindBoundary:
				result.Boundaries = append(result.Boundaries, node.Statement)
			case KindTension:
				// Only the first active tension is reported as primary.
				if result.PrimaryTension == "" {
					result.PrimaryTension = node.ID
				}
			}

			// Track low-confidence strong beliefs.
			if node.Strength >= 0.7 && node.Confidence < 0.4 {
				result.LowConfidenceInferences = append(result.LowConfidenceInferences, node.Statement)
			}
		}
	}

	// Compute tendency from the activated set.
	result.Tendency = e.computeTendency(result.ActiveBeliefs)

	return result, nil
}

// computeTendency aggregates active beliefs into a direction label.
func (e *Engine) computeTendency(activeIDs []string) string {
	if len(activeIDs) == 0 {
		return "neutral"
	}

	var valenceSum float64
	var boundaryCount, valueCount, relationalCount int

	for _, id := range activeIDs {
		node := e.graph.Get(id)
		if node == nil {
			continue
		}
		valenceSum += node.Valence
		switch node.Kind {
		case KindBoundary:
			boundaryCount++
		case KindValue:
			valueCount++
		case KindRelational:
			relationalCount++
		}
	}

	avgValence := valenceSum / float64(len(activeIDs))

	// Decide tendency based on proportions.
	if avgValence < -0.3 && boundaryCount > 0 {
		return "defensive"
	}
	if avgValence > 0.3 && relationalCount > 0 {
		return "warm"
	}
	if valueCount > relationalCount && avgValence > 0 {
		return "principled"
	}
	if relationalCount > valueCount {
		return "attentive"
	}
	if avgValence < -0.1 {
		return "cautious"
	}
	return "open"
}

// ── Update Application ──

// Apply atomically applies a BeliefUpdateProposal to the graph.
// Returns an error if any single update fails (the entire proposal is rolled back).
func (e *Engine) Apply(proposal *BeliefUpdateProposal) error {
	if proposal == nil {
		return fmt.Errorf("belief: cannot apply nil proposal")
	}

	e.mu.Lock()
	defer e.mu.Unlock()

	// Validate first so we don't partially apply.
	for _, u := range proposal.Updates {
		if err := e.validateUpdate(u); err != nil {
			return fmt.Errorf("belief: invalid update in proposal: %w", err)
		}
	}
	for _, n := range proposal.ProposedNew {
		if err := n.Validate(); err != nil {
			return fmt.Errorf("belief: invalid proposed node: %w", err)
		}
	}
	if proposal.ProposedTension != nil {
		if err := proposal.ProposedTension.Validate(); err != nil {
			return fmt.Errorf("belief: invalid proposed tension: %w", err)
		}
	}

	// Apply new nodes.
	for _, n := range proposal.ProposedNew {
		now := time.Now()
		n.CreatedAt = now
		n.LastUpdatedAt = now

		if err := e.graph.Add(n); err != nil {
			return fmt.Errorf("belief: failed to add proposed node %q: %w", n.ID, err)
		}

		e.appendAudit(AuditEntry{
			Timestamp:  now,
			Kind:       string(UpdateCreation),
			TargetID:   n.ID,
			Detail:     fmt.Sprintf("created: %s", n.Statement),
			Provenance: proposal.Provenance,
		})
	}

	// Apply tension node.
	if proposal.ProposedTension != nil {
		tn := proposal.ProposedTension
		tn.CreatedAt = time.Now()
		tn.LastUpdatedAt = time.Now()

		if err := e.graph.Add(tn); err != nil {
			return fmt.Errorf("belief: failed to add tension node %q: %w", tn.ID, err)
		}

		e.appendAudit(AuditEntry{
			Timestamp:  time.Now(),
			Kind:       string(UpdateCreation),
			TargetID:   tn.ID,
			Detail:     fmt.Sprintf("tension created: %s", tn.Statement),
			Provenance: proposal.Provenance,
		})
	}

	// Apply updates.
	for _, u := range proposal.Updates {
		if err := e.applyOne(u, proposal.Provenance); err != nil {
			return fmt.Errorf("belief: failed to apply update to %q: %w", u.TargetID, err)
		}
	}

	return nil
}

func (e *Engine) validateUpdate(u UpdateRecord) error {
	switch u.Kind {
	case UpdateReinforce, UpdateWeaken:
		if u.Delta < 0 || u.Delta > 1 {
			return fmt.Errorf("delta must be in [0, 1], got %f", u.Delta)
		}
	case UpdateValenceShift:
		if u.ValenceTo < -1 || u.ValenceTo > 1 {
			return fmt.Errorf("valence_to must be in [-1, 1], got %f", u.ValenceTo)
		}
	case UpdateResolution, UpdateSuppression:
		// No extra validation needed.
	case UpdateEvidence:
		if u.Evidence == "" {
			return fmt.Errorf("evidence must not be empty")
		}
	case UpdateCreation:
		// New nodes are handled separately.
	default:
		return fmt.Errorf("unknown update kind: %s", u.Kind)
	}

	if u.TargetID == "" {
		return fmt.Errorf("target_id is required")
	}
	return nil
}

func (e *Engine) applyOne(u UpdateRecord, provenance string) error {
	node := e.graph.Get(u.TargetID)
	if node == nil {
		return fmt.Errorf("node %q not found", u.TargetID)
	}

	now := time.Now()

	switch u.Kind {
	case UpdateReinforce:
		delta := u.Delta * node.Plasticity // plasticity bounds the change
		node.Strength = math.Min(1.0, node.Strength+delta)
		node.Confidence = math.Min(1.0, node.Confidence+delta*0.5)
		node.LastUpdatedAt = now

	case UpdateWeaken:
		delta := u.Delta * node.Plasticity
		node.Strength = math.Max(0.0, node.Strength-delta)
		node.Confidence = math.Max(0.0, node.Confidence-delta*0.3)
		node.LastUpdatedAt = now

	case UpdateValenceShift:
		shift := (u.ValenceTo - node.Valence) * node.Plasticity
		node.Valence = clipTo(node.Valence+shift, -1, 1)
		node.LastUpdatedAt = now

	case UpdateEvidence:
		node.Evidence = append(node.Evidence, u.Evidence)
		// Cap evidence list to prevent unbounded growth.
		if len(node.Evidence) > 100 {
			node.Evidence = node.Evidence[len(node.Evidence)-100:]
		}
		node.LastUpdatedAt = now

	case UpdateResolution:
		// Mark tension as resolved by reducing its strength to near-zero.
		node.Strength = 0.01
		node.Confidence = 0.01
		node.LastUpdatedAt = now
		if u.Evidence != "" {
			node.Evidence = append(node.Evidence, u.Evidence)
		}

	case UpdateSuppression:
		// Temporarily reduce strength without changing confidence.
		node.Strength = math.Max(0.05, node.Strength-0.3)
		node.LastUpdatedAt = now
	}

	e.appendAudit(AuditEntry{
		Timestamp:  now,
		Kind:       string(u.Kind),
		TargetID:   u.TargetID,
		Delta:      u.Delta,
		Detail:     u.Note,
		Provenance: provenance,
	})

	return nil
}

// ── Decay ──

// ApplyDecay weakens all beliefs that haven't been updated recently.
// Called periodically (e.g., once per hour or during nighttime).
// Root beliefs are immune to decay.
func (e *Engine) ApplyDecay(daysElapsed float64) int {
	e.mu.Lock()
	defer e.mu.Unlock()

	if daysElapsed <= 0 {
		return 0
	}

	var count int
	for _, node := range e.graph.List() {
		if node.IsRoot() {
			continue
		}
		if node.Kind == KindTension {
			continue // tensions are handled separately
		}

		age := time.Since(node.LastUpdatedAt).Hours() / 24 // days
		if age < 1 {
			continue // only decay beliefs older than 1 day
		}

		decay := e.decayRate * daysElapsed * node.Plasticity
		newStrength := math.Max(0.1, node.Strength-decay) // floor at 0.1
		node.Strength = newStrength
		node.LastUpdatedAt = time.Now()
		count++
	}

	return count
}

// StaleTensions returns tension nodes that have been unresolved for too long.
func (e *Engine) StaleTensions() []*BeliefNode {
	e.mu.RLock()
	defer e.mu.RUnlock()

	if e.maxTensionAge <= 0 {
		return nil
	}

	var out []*BeliefNode
	for _, t := range e.graph.Tensions() {
		if time.Since(t.CreatedAt) > e.maxTensionAge {
			out = append(out, t)
		}
	}
	return out
}

// ── Belief Update Proposal (high-level API) ──

// Reinforce creates a proposal to strengthen a belief.
func (e *Engine) Reinforce(targetID string, delta float64, evidence, provenance string) *BeliefUpdateProposal {
	if delta <= 0 {
		delta = 0.1
	}
	updates := []UpdateRecord{{
		Kind:     UpdateReinforce,
		TargetID: targetID,
		Delta:    delta,
		Evidence: evidence,
		Source:   SourceInteraction,
		Note:     "reinforced by interaction",
	}}
	if evidence != "" {
		updates = append(updates, UpdateRecord{
			Kind:     UpdateEvidence,
			TargetID: targetID,
			Evidence: evidence,
			Source:   SourceInteraction,
		})
	}
	return &BeliefUpdateProposal{
		Updates:    updates,
		Reason:     "reinforce " + targetID,
		Provenance: provenance,
	}
}

// Weaken creates a proposal to weaken a belief.
func (e *Engine) Weaken(targetID string, delta float64, evidence, provenance string) *BeliefUpdateProposal {
	if delta <= 0 {
		delta = 0.1
	}
	updates := []UpdateRecord{{
		Kind:     UpdateWeaken,
		TargetID: targetID,
		Delta:    delta,
		Evidence: evidence,
		Source:   SourceInteraction,
		Note:     "weakened by interaction",
	}}
	return &BeliefUpdateProposal{
		Updates:    updates,
		Reason:     "weaken " + targetID,
		Provenance: provenance,
	}
}

// ── Audit ──

// AuditEntry records a single belief system change.
type AuditEntry struct {
	Timestamp  time.Time `json:"timestamp"`
	Kind       string    `json:"kind"`
	TargetID   string    `json:"target_id"`
	Delta      float64   `json:"delta,omitempty"`
	Detail     string    `json:"detail,omitempty"`
	Provenance string    `json:"provenance,omitempty"`
}

// AuditLog returns a copy of the full audit log.
func (e *Engine) AuditLog() []AuditEntry {
	e.mu.RLock()
	defer e.mu.RUnlock()
	out := make([]AuditEntry, len(e.auditLog))
	copy(out, e.auditLog)
	return out
}

// RecentAudit returns the N most recent audit entries.
func (e *Engine) RecentAudit(n int) []AuditEntry {
	e.mu.RLock()
	defer e.mu.RUnlock()

	if n <= 0 || n > len(e.auditLog) {
		n = len(e.auditLog)
	}
	out := make([]AuditEntry, n)
	copy(out, e.auditLog[len(e.auditLog)-n:])
	return out
}

func (e *Engine) appendAudit(entry AuditEntry) {
	e.auditLog = append(e.auditLog, entry)
	// Cap the audit log at 10,000 entries.
	if len(e.auditLog) > 10000 {
		e.auditLog = e.auditLog[len(e.auditLog)-10000:]
	}
}

func clipTo(v, min, max float64) float64 {
	if v < min {
		return min
	}
	if v > max {
		return max
	}
	return v
}
