package knowledge

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
)

// WikiPage is a structured knowledge page generated by LLM digestion.
type WikiPage struct {
	ID        string            `json:"id"`
	SourceID  string            `json:"source_id"`
	Title     string            `json:"title"`
	Summary   string            `json:"summary"`
	Content   string            `json:"content"`
	Links     []string          `json:"links,omitempty"`
	Sources   []WikiSourceRef   `json:"sources,omitempty"`
	Tags      []string          `json:"tags,omitempty"`
	Metadata  map[string]string `json:"metadata,omitempty"`
	CreatedAt time.Time         `json:"created_at"`
	UpdatedAt time.Time         `json:"updated_at"`
}

// WikiSourceRef traces back to original content.
type WikiSourceRef struct {
	ChunkID    string `json:"chunk_id"`
	SourceName string `json:"source_name"`
	Excerpt    string `json:"excerpt"`
}

// WikiDigester generates structured Wiki pages from raw knowledge chunks using an LLM.
type WikiDigester interface {
	Digest(ctx context.Context, sourceName string, chunks []string) ([]WikiPage, error)
}

// WikiStore manages structured wiki pages alongside the chunk store.
type WikiStore struct {
	mu       sync.RWMutex
	pages    map[string]*WikiPage
	digester WikiDigester
	kvs      kvStore
}

func NewWikiStore(digester WikiDigester) *WikiStore {
	return &WikiStore{
		pages:    make(map[string]*WikiPage),
		digester: digester,
	}
}

func (ws *WikiStore) SetKVStore(kvs kvStore) {
	ws.mu.Lock()
	defer ws.mu.Unlock()
	ws.kvs = kvs

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	var pages map[string]*WikiPage
	found, err := kvs.Get(ctx, "wiki_pages", &pages)
	if err != nil {
		slog.Warn("wiki: KV load failed", "err", err)
		return
	}
	if found && len(pages) > 0 {
		for id, p := range pages {
			if _, exists := ws.pages[id]; !exists {
				ws.pages[id] = p
			}
		}
		slog.Info("wiki: loaded from KV", "pages", len(pages))
	}
}

func (ws *WikiStore) FlushToKV() {
	ws.mu.RLock()
	kvs := ws.kvs
	pages := make(map[string]*WikiPage, len(ws.pages))
	for k, v := range ws.pages {
		cp := *v
		pages[k] = &cp
	}
	ws.mu.RUnlock()

	if kvs == nil {
		return
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	if err := kvs.Put(ctx, "wiki_pages", pages); err != nil {
		slog.Error("wiki: flush to KV failed", "err", err)
	}
}

// DigestSource generates wiki pages from a knowledge source's chunks.
func (ws *WikiStore) DigestSource(ctx context.Context, sourceID, sourceName string, chunks []Chunk) error {
	if ws.digester == nil {
		return fmt.Errorf("wiki: no digester configured")
	}

	texts := make([]string, 0, len(chunks))
	for _, c := range chunks {
		texts = append(texts, c.Content)
	}

	pages, err := ws.digester.Digest(ctx, sourceName, texts)
	if err != nil {
		return fmt.Errorf("wiki: digest failed: %w", err)
	}

	ws.mu.Lock()
	defer ws.mu.Unlock()

	for i := range pages {
		pages[i].ID = uuid.New().String()
		pages[i].SourceID = sourceID
		pages[i].CreatedAt = time.Now()
		pages[i].UpdatedAt = time.Now()

		for j, ref := range pages[i].Sources {
			if ref.ChunkID == "" && j < len(chunks) {
				pages[i].Sources[j].ChunkID = chunks[j].ID
				pages[i].Sources[j].SourceName = sourceName
			}
		}

		ws.pages[pages[i].ID] = &pages[i]
	}

	slog.Info("wiki: digested source", "source", sourceName, "pages", len(pages))

	if ws.kvs != nil {
		go ws.FlushToKV()
	}
	return nil
}

// Search finds wiki pages matching a query by title/summary/content.
func (ws *WikiStore) Search(query string, limit int) []*WikiPage {
	ws.mu.RLock()
	defer ws.mu.RUnlock()

	if limit <= 0 {
		limit = 5
	}
	q := strings.ToLower(query)
	var results []*WikiPage
	for _, p := range ws.pages {
		if strings.Contains(strings.ToLower(p.Title), q) ||
			strings.Contains(strings.ToLower(p.Summary), q) ||
			strings.Contains(strings.ToLower(p.Content), q) {
			cp := *p
			results = append(results, &cp)
		}
	}
	sort.Slice(results, func(i, j int) bool {
		return results[i].UpdatedAt.After(results[j].UpdatedAt)
	})
	if len(results) > limit {
		results = results[:limit]
	}
	return results
}

// GetPage returns a wiki page by ID.
func (ws *WikiStore) GetPage(id string) *WikiPage {
	ws.mu.RLock()
	defer ws.mu.RUnlock()
	if p, ok := ws.pages[id]; ok {
		cp := *p
		return &cp
	}
	return nil
}

// ListPages returns all wiki pages.
func (ws *WikiStore) ListPages() []*WikiPage {
	ws.mu.RLock()
	defer ws.mu.RUnlock()
	out := make([]*WikiPage, 0, len(ws.pages))
	for _, p := range ws.pages {
		cp := *p
		out = append(out, &cp)
	}
	sort.Slice(out, func(i, j int) bool {
		return out[i].UpdatedAt.After(out[j].UpdatedAt)
	})
	return out
}

// RemoveBySource removes all wiki pages for a source.
func (ws *WikiStore) RemoveBySource(sourceID string) int {
	ws.mu.Lock()
	defer ws.mu.Unlock()
	removed := 0
	for id, p := range ws.pages {
		if p.SourceID == sourceID {
			delete(ws.pages, id)
			removed++
		}
	}
	if removed > 0 && ws.kvs != nil {
		go ws.FlushToKV()
	}
	return removed
}

// Stats returns wiki store statistics.
func (ws *WikiStore) Stats() WikiStats {
	ws.mu.RLock()
	defer ws.mu.RUnlock()
	sources := make(map[string]bool)
	for _, p := range ws.pages {
		sources[p.SourceID] = true
	}
	return WikiStats{
		Pages:   len(ws.pages),
		Sources: len(sources),
	}
}

type WikiStats struct {
	Pages   int `json:"pages"`
	Sources int `json:"sources"`
}

// LLMWikiDigester uses an LLM to generate wiki pages from chunks.
type LLMWikiDigester struct {
	chat func(ctx context.Context, prompt string) (string, error)
}

func NewLLMWikiDigester(chatFn func(ctx context.Context, prompt string) (string, error)) *LLMWikiDigester {
	return &LLMWikiDigester{chat: chatFn}
}

func (d *LLMWikiDigester) Digest(ctx context.Context, sourceName string, chunks []string) ([]WikiPage, error) {
	combined := strings.Join(chunks, "\n---\n")
	if len(combined) > 32000 {
		combined = combined[:32000] + "\n...(truncated)"
	}

	prompt := fmt.Sprintf(`You are a knowledge organizer. Read the following content from "%s" and generate structured Wiki pages.

For each logical topic you identify, create a JSON object with:
- "title": concise page title
- "summary": 1-2 sentence overview
- "content": full structured content in Markdown (use headings, lists, etc.)
- "tags": relevant keywords (array of strings)
- "links": titles of related pages in this set (for cross-linking)
- "sources": array of {"excerpt": "key quote from original"} for traceability

Return a JSON array of these page objects. Aim for 2-5 pages depending on content richness.
Keep content factual and well-organized. Write in the same language as the source material.

Content:
%s`, sourceName, combined)

	reply, err := d.chat(ctx, prompt)
	if err != nil {
		return nil, fmt.Errorf("LLM digest: %w", err)
	}

	reply = strings.TrimSpace(reply)
	if idx := strings.Index(reply, "["); idx >= 0 {
		reply = reply[idx:]
	}
	if idx := strings.LastIndex(reply, "]"); idx >= 0 {
		reply = reply[:idx+1]
	}

	var pages []WikiPage
	if err := json.Unmarshal([]byte(reply), &pages); err != nil {
		return nil, fmt.Errorf("parse wiki pages: %w (raw: %.200s)", err, reply)
	}
	return pages, nil
}
